# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20170719_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='Thunderdome', max_length=255),
        ),
    ]
