# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0002_auto_20170719_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='all_books', to='books_authors.Author'),
        ),
    ]
