# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0004_auto_20170719_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books_authors.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Null', max_length=1000),
        ),
    ]
