# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0005_auto_20170720_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='something',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
