# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0006_author_something'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='something',
        ),
    ]
